import { MigrationInterface, QueryRunner } from "typeorm";

export class SnakeCaseColumns1790311452515 implements MigrationInterface {
    name = 'SnakeCaseColumns1790311452515'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP FOREIGN KEY \`FK_f4809f4f9ad4a220959788def42\``);
        await queryRunner.query(`ALTER TABLE \`chats\` DROP FOREIGN KEY \`FK_59279cb5c542a95d0f22a05d1ab\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_692a909ee0fa9383e7859f9b406\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP FOREIGN KEY \`FK_1aa6ccc6c5849166c8b8f8583eb\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP FOREIGN KEY \`FK_ca46e351b720421fe72bfe32454\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP FOREIGN KEY \`FK_d9aee364981beff89d2d5097341\``);
        await queryRunner.query(`ALTER TABLE \`analysis\` DROP FOREIGN KEY \`FK_ee32273d2ac88ece93b77592ad2\``);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` DROP FOREIGN KEY \`FK_18766411cf5f32431854fcdaad4\``);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` DROP FOREIGN KEY \`FK_4458280c71793a4337a4bc61aea\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_36bc604c820bb9adc4c75cd4115\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_message_details\` DROP FOREIGN KEY \`FK_dbd102d2263ac2df6b3accc3dca\``);
        await queryRunner.query(`ALTER TABLE \`members\` DROP FOREIGN KEY \`FK_136a2347b3428cc7b4f1baef918\``);
        await queryRunner.query(`ALTER TABLE \`members\` DROP FOREIGN KEY \`FK_839756572a2c38eb5a3b563126e\``);
        await queryRunner.query(`DROP INDEX \`IDX_0886c2d010557204bd4f3dd7bf\` ON \`contacts\``);
        await queryRunner.query(`DROP INDEX \`IDX_5c2c2331481cf3e7697e9f5e29\` ON \`contacts\``);
        await queryRunner.query(`DROP INDEX \`IDX_1e3d0240b49c40521aaeb95329\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_f573d0683e090a667792f83bf0\` ON \`whatsapp_configs\``);
        await queryRunner.query(`DROP INDEX \`IDX_cf6aa5dcde4a7505c85956bc9b\` ON \`chat_assignments\``);
        await queryRunner.query(`DROP INDEX \`IDX_65fda6262770c7c6f9e1d14b06\` ON \`whatsapp_message_details\``);
        await queryRunner.query(`DROP INDEX \`IDX_19ae8b65015c5afea9c0348ca0\` ON \`members\``);
        await queryRunner.query(`ALTER TABLE \`companies\` DROP COLUMN \`phoneNumber\``);
        await queryRunner.query(`ALTER TABLE \`companies\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`companies\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`companies\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP COLUMN \`waId\``);
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP COLUMN \`firstNames\``);
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP COLUMN \`lastNames\``);
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP COLUMN \`phoneNumber\``);
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP COLUMN \`lastInteractionAt\``);
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP COLUMN \`companyId\``);
        await queryRunner.query(`ALTER TABLE \`chats\` DROP COLUMN \`lastMessageAt\``);
        await queryRunner.query(`ALTER TABLE \`chats\` DROP COLUMN \`endedAt\``);
        await queryRunner.query(`ALTER TABLE \`chats\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`chats\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`chats\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`chats\` DROP COLUMN \`clientId\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`firstName\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`lastName\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`phoneNumber\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`chatId\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`fromAgentId\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`toAgentId\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP COLUMN \`apiVersion\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP COLUMN \`apiBaseUrl\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP COLUMN \`businessId\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP COLUMN \`accessToken\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP COLUMN \`phoneNumberId\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP COLUMN \`webhookUrl\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP COLUMN \`webhookVerifyToken\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP COLUMN \`isActive\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`analysis\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`analysis\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`analysis\` DROP COLUMN \`messageId\``);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` DROP COLUMN \`scorePos\``);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` DROP COLUMN \`scoreNeu\``);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` DROP COLUMN \`scoreNeg\``);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` DROP COLUMN \`assignedAt\``);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` DROP COLUMN \`unassignedAt\``);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` DROP COLUMN \`chatId\``);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` DROP COLUMN \`agentId\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP COLUMN \`senderType\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP COLUMN \`senderId\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP COLUMN \`mediaUrl\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP COLUMN \`chatId\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_message_details\` DROP COLUMN \`waId\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_message_details\` DROP COLUMN \`configId\``);
        await queryRunner.query(`ALTER TABLE \`members\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`members\` DROP COLUMN \`companyId\``);
        await queryRunner.query(`ALTER TABLE \`companies\` ADD \`phone_number\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`companies\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`companies\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`companies\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD \`wa_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD UNIQUE INDEX \`IDX_452c624ef116a33bdcdb326305\` (\`wa_id\`)`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD \`first_names\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD \`last_names\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD \`phone_number\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD \`last_interaction_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD \`company_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`chats\` ADD \`last_message_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`chats\` ADD \`ended_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`chats\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`chats\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`chats\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`chats\` ADD \`client_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`user_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`first_name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`last_name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`phone_number\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_17d1817f241f10a3dbafb169fd\` (\`phone_number\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`chat_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`from_agent_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`to_agent_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD \`api_version\` varchar(255) NOT NULL DEFAULT 'v22.0'`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD \`api_base_url\` varchar(255) NOT NULL DEFAULT 'https://graph.facebook.com'`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD \`business_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD UNIQUE INDEX \`IDX_463105c054575a99967512082b\` (\`business_id\`)`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD \`access_token\` varchar(512) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD \`phone_number_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD \`webhook_url\` varchar(512) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD \`webhook_verify_token\` varchar(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD \`is_active\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`analysis\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`analysis\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`analysis\` ADD \`message_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` ADD \`score_pos\` decimal(5,4) NOT NULL DEFAULT '0.0000'`);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` ADD \`score_neu\` decimal(5,4) NOT NULL DEFAULT '0.0000'`);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` ADD \`score_neg\` decimal(5,4) NOT NULL DEFAULT '0.0000'`);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` ADD \`assigned_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` ADD \`unassigned_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` ADD \`chat_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` ADD \`agent_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD \`sender_type\` enum ('agent', 'user', 'client', 'system') NOT NULL DEFAULT 'system'`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD \`sender_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD \`media_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD \`chat_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_message_details\` ADD \`wa_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_message_details\` ADD UNIQUE INDEX \`IDX_bfddba6bf04790da8c8d139942\` (\`wa_id\`)`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_message_details\` ADD \`config_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`members\` ADD \`user_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`members\` ADD \`company_id\` varchar(36) NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_071ac814511237f779535feabc\` ON \`contacts\` (\`phone_number\`, \`company_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_b0530c1cfad7e6de47b8f2c652\` ON \`chat_assignments\` (\`chat_id\`, \`agent_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_4a29ebc29e4d5c5624cde154ef\` ON \`members\` (\`user_id\`, \`company_id\`)`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD CONSTRAINT \`FK_b53945f3dfe982678bfeb5e1b4f\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chats\` ADD CONSTRAINT \`FK_a0a4ca2299b536cf241d7b9f4bb\` FOREIGN KEY (\`client_id\`) REFERENCES \`contacts\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_9a8a82462cab47c73d25f49261f\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD CONSTRAINT \`FK_bc604bbc4bae001d016b2f4e000\` FOREIGN KEY (\`chat_id\`) REFERENCES \`chats\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD CONSTRAINT \`FK_a594454369032dba6d018bc0e41\` FOREIGN KEY (\`from_agent_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD CONSTRAINT \`FK_4eaef34558bb4ab517569149f97\` FOREIGN KEY (\`to_agent_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analysis\` ADD CONSTRAINT \`FK_10d5c2d46c90154e46c486e74c0\` FOREIGN KEY (\`message_id\`) REFERENCES \`messages\`(\`message_id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` ADD CONSTRAINT \`FK_7aa6cca8a7442e2499472e84c1d\` FOREIGN KEY (\`chat_id\`) REFERENCES \`chats\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` ADD CONSTRAINT \`FK_52a42120f2974be27ec7f9329ff\` FOREIGN KEY (\`agent_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_7540635fef1922f0b156b9ef74f\` FOREIGN KEY (\`chat_id\`) REFERENCES \`chats\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_message_details\` ADD CONSTRAINT \`FK_2dace39a1a73bd655f344d63a78\` FOREIGN KEY (\`config_id\`) REFERENCES \`whatsapp_configs\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`members\` ADD CONSTRAINT \`FK_da404b5fd9c390e25338996e2d1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`members\` ADD CONSTRAINT \`FK_e0aa1c0f8c54664b4c09bff6c41\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`members\` DROP FOREIGN KEY \`FK_e0aa1c0f8c54664b4c09bff6c41\``);
        await queryRunner.query(`ALTER TABLE \`members\` DROP FOREIGN KEY \`FK_da404b5fd9c390e25338996e2d1\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_message_details\` DROP FOREIGN KEY \`FK_2dace39a1a73bd655f344d63a78\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_7540635fef1922f0b156b9ef74f\``);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` DROP FOREIGN KEY \`FK_52a42120f2974be27ec7f9329ff\``);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` DROP FOREIGN KEY \`FK_7aa6cca8a7442e2499472e84c1d\``);
        await queryRunner.query(`ALTER TABLE \`analysis\` DROP FOREIGN KEY \`FK_10d5c2d46c90154e46c486e74c0\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP FOREIGN KEY \`FK_4eaef34558bb4ab517569149f97\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP FOREIGN KEY \`FK_a594454369032dba6d018bc0e41\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP FOREIGN KEY \`FK_bc604bbc4bae001d016b2f4e000\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_9a8a82462cab47c73d25f49261f\``);
        await queryRunner.query(`ALTER TABLE \`chats\` DROP FOREIGN KEY \`FK_a0a4ca2299b536cf241d7b9f4bb\``);
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP FOREIGN KEY \`FK_b53945f3dfe982678bfeb5e1b4f\``);
        await queryRunner.query(`DROP INDEX \`IDX_4a29ebc29e4d5c5624cde154ef\` ON \`members\``);
        await queryRunner.query(`DROP INDEX \`IDX_b0530c1cfad7e6de47b8f2c652\` ON \`chat_assignments\``);
        await queryRunner.query(`DROP INDEX \`IDX_071ac814511237f779535feabc\` ON \`contacts\``);
        await queryRunner.query(`ALTER TABLE \`members\` DROP COLUMN \`company_id\``);
        await queryRunner.query(`ALTER TABLE \`members\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_message_details\` DROP COLUMN \`config_id\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_message_details\` DROP INDEX \`IDX_bfddba6bf04790da8c8d139942\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_message_details\` DROP COLUMN \`wa_id\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP COLUMN \`chat_id\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP COLUMN \`media_url\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP COLUMN \`sender_id\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP COLUMN \`sender_type\``);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` DROP COLUMN \`agent_id\``);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` DROP COLUMN \`chat_id\``);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` DROP COLUMN \`unassigned_at\``);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` DROP COLUMN \`assigned_at\``);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` DROP COLUMN \`score_neg\``);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` DROP COLUMN \`score_neu\``);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` DROP COLUMN \`score_pos\``);
        await queryRunner.query(`ALTER TABLE \`analysis\` DROP COLUMN \`message_id\``);
        await queryRunner.query(`ALTER TABLE \`analysis\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`analysis\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP COLUMN \`is_active\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP COLUMN \`webhook_verify_token\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP COLUMN \`webhook_url\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP COLUMN \`phone_number_id\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP COLUMN \`access_token\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP INDEX \`IDX_463105c054575a99967512082b\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP COLUMN \`business_id\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP COLUMN \`api_base_url\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` DROP COLUMN \`api_version\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`to_agent_id\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`from_agent_id\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`chat_id\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_17d1817f241f10a3dbafb169fd\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`phone_number\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`last_name\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`first_name\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`chats\` DROP COLUMN \`client_id\``);
        await queryRunner.query(`ALTER TABLE \`chats\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`chats\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`chats\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`chats\` DROP COLUMN \`ended_at\``);
        await queryRunner.query(`ALTER TABLE \`chats\` DROP COLUMN \`last_message_at\``);
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP COLUMN \`company_id\``);
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP COLUMN \`last_interaction_at\``);
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP COLUMN \`phone_number\``);
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP COLUMN \`last_names\``);
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP COLUMN \`first_names\``);
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP INDEX \`IDX_452c624ef116a33bdcdb326305\``);
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP COLUMN \`wa_id\``);
        await queryRunner.query(`ALTER TABLE \`companies\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`companies\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`companies\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`companies\` DROP COLUMN \`phone_number\``);
        await queryRunner.query(`ALTER TABLE \`members\` ADD \`companyId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`members\` ADD \`userId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_message_details\` ADD \`configId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_message_details\` ADD \`waId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD \`chatId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD \`mediaUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD \`senderId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD \`senderType\` enum ('agent', 'user', 'client', 'system') NOT NULL DEFAULT 'system'`);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` ADD \`agentId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` ADD \`chatId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` ADD \`unassignedAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` ADD \`assignedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` ADD \`scoreNeg\` decimal(5,4) NOT NULL DEFAULT '0.0000'`);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` ADD \`scoreNeu\` decimal(5,4) NOT NULL DEFAULT '0.0000'`);
        await queryRunner.query(`ALTER TABLE \`sentiment_analysis\` ADD \`scorePos\` decimal(5,4) NOT NULL DEFAULT '0.0000'`);
        await queryRunner.query(`ALTER TABLE \`analysis\` ADD \`messageId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`analysis\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`analysis\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD \`isActive\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD \`webhookVerifyToken\` varchar(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD \`webhookUrl\` varchar(512) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD \`phoneNumberId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD \`accessToken\` varchar(512) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD \`businessId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD \`apiBaseUrl\` varchar(255) NOT NULL DEFAULT 'https://graph.facebook.com'`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_configs\` ADD \`apiVersion\` varchar(255) NOT NULL DEFAULT 'v22.0'`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`toAgentId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`fromAgentId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`chatId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`phoneNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`lastName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`firstName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`userId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`chats\` ADD \`clientId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`chats\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`chats\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`chats\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`chats\` ADD \`endedAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`chats\` ADD \`lastMessageAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD \`companyId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD \`lastInteractionAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD \`phoneNumber\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD \`lastNames\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD \`firstNames\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD \`waId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`companies\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`companies\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`companies\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`companies\` ADD \`phoneNumber\` varchar(50) NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_19ae8b65015c5afea9c0348ca0\` ON \`members\` (\`userId\`, \`companyId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_65fda6262770c7c6f9e1d14b06\` ON \`whatsapp_message_details\` (\`waId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_cf6aa5dcde4a7505c85956bc9b\` ON \`chat_assignments\` (\`chatId\`, \`agentId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_f573d0683e090a667792f83bf0\` ON \`whatsapp_configs\` (\`businessId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_1e3d0240b49c40521aaeb95329\` ON \`users\` (\`phoneNumber\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_5c2c2331481cf3e7697e9f5e29\` ON \`contacts\` (\`waId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_0886c2d010557204bd4f3dd7bf\` ON \`contacts\` (\`phoneNumber\`, \`companyId\`)`);
        await queryRunner.query(`ALTER TABLE \`members\` ADD CONSTRAINT \`FK_839756572a2c38eb5a3b563126e\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`members\` ADD CONSTRAINT \`FK_136a2347b3428cc7b4f1baef918\` FOREIGN KEY (\`companyId\`) REFERENCES \`companies\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_message_details\` ADD CONSTRAINT \`FK_dbd102d2263ac2df6b3accc3dca\` FOREIGN KEY (\`configId\`) REFERENCES \`whatsapp_configs\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_36bc604c820bb9adc4c75cd4115\` FOREIGN KEY (\`chatId\`) REFERENCES \`chats\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` ADD CONSTRAINT \`FK_4458280c71793a4337a4bc61aea\` FOREIGN KEY (\`chatId\`) REFERENCES \`chats\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_assignments\` ADD CONSTRAINT \`FK_18766411cf5f32431854fcdaad4\` FOREIGN KEY (\`agentId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analysis\` ADD CONSTRAINT \`FK_ee32273d2ac88ece93b77592ad2\` FOREIGN KEY (\`messageId\`) REFERENCES \`messages\`(\`message_id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD CONSTRAINT \`FK_d9aee364981beff89d2d5097341\` FOREIGN KEY (\`toAgentId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD CONSTRAINT \`FK_ca46e351b720421fe72bfe32454\` FOREIGN KEY (\`chatId\`) REFERENCES \`chats\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD CONSTRAINT \`FK_1aa6ccc6c5849166c8b8f8583eb\` FOREIGN KEY (\`fromAgentId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_692a909ee0fa9383e7859f9b406\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chats\` ADD CONSTRAINT \`FK_59279cb5c542a95d0f22a05d1ab\` FOREIGN KEY (\`clientId\`) REFERENCES \`contacts\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD CONSTRAINT \`FK_f4809f4f9ad4a220959788def42\` FOREIGN KEY (\`companyId\`) REFERENCES \`companies\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
